### ISSUE TITLE
Mouse Drag Shows as if Depressed Mouse Click with <a style={{"display":"block"}}

### ISSUE THREAD

**Issue by chris2fr** [sag1v/react-elastic-carousel#117]
**Describe the bug**

When I mouse-scroll with a `<Link style={{"display":"block"}} ` around the item div, I seem to be stuck with a mouse-down event without the mouse-up and the mouse-scroll works, but locks me it.

**To Reproduce**

1. Go to https://alpha.mann.fr/ or https://codesandbox.io/s/gallant-bush-96xqw?file=/src/App.js
2. Click on any item
3. Scroll left or right with the mouse
4. See that you are stuck there.

```
        <Carousel
          enableMouseSwipe={true}
        >
          <div key="slide-digital" className={"mann-carousel-item"}>
            <Link to="/tag/digital/" style={{ display: "block" }}>
```

**Expected behavior**

The mouse scrolling should only take place as the left-button is down.

**Sandbox link**

https://codesandbox.io/s/gallant-bush-96xqw?file=/src/App.js

**Additional context**

This is probably a new case.

**Comment by sag1v** [comment]
@chris2fr thanks.
You mean that the image or link is dragged instead of the carousel sliding? 
If so, this is a default behaviour of the browser when it comes to links and images (or any draggable elements). I suggests adding The `draggable="false"` to the image/link to prevent the drag effect. 
I tried it with your sandbox example and it seems to do the trick.

**Comment by chris2fr** [comment]
Yes draggable="false"
THANK YOU SO MUCH

**Comment by chris2fr** [comment]
Update to the documentation maybe. Shall I?

**Comment by sag1v** [comment]
Well its not really related to this library in specific, its just how HTML works and implemented in browsers.

**Comment by sag1v** [comment]
Can we close this one?
