### ISSUE TITLE
Carousel items are not visible

### ISSUE THREAD

**Issue by EvangelosVorgias** [sag1v/react-elastic-carousel#226]
I recently tried to add the carousel to my website. I tried to follow the steps in the installation guide, however I got an error "unable to resolve dependency tree". To circumvent this, I used the command: npm install --save react-elastic-carousel --legacy-peer-deps. I then installed the other required library. The carousel now appears almost as intended. The buttons are there, the circles at the bottom are there and when I change the height of the items the carousel height changes as well. However, the items are not visible. Changing the background, color or children of the items themselves does not do anything (neither using className nor using style).

An additional weird thing is that when I first load the page and press one one of the buttons to go to a different item, the carousel height seems to change, but it does not change when I go back to the previous item. This might however be irrelevant or stem from somewhere else.

I'm new to web development, so if I should tell you which things I'm using, please also write how I can get that information. I'm trying this on the newest version of Firefox, but it does not work on my mobile phone browser either, so I don't think that it's a browser related issue.

**Comment by munafio** [comment]
@EvangelosVorgias I faced the same issue, but if you inspect the elements (items) you can see that the width is 0 thats why the div or the element can not be visible! 
all you have to do is to set a static width or percentage for the element (item/slide) .. in my case I set the width to 100% (full) to fill the space given.

so now if you have 8 items, the space given for each item will be filled because of the `width: 100%`.

**Comment by EvangelosVorgias** [comment]
Thanks
