### ISSUE TITLE
Not able to scroll to below or upward

### ISSUE THREAD

**Issue by emt-mocha** [sag1v/react-elastic-carousel#40]
I found some issue with the Carousel over mobile screen. The problem starts when we set the carousel height to 100vh + full width, once you reach to the carousel section, thats it you cant scroll up or below to previous or next sections. But scrolling left and right to view the content inside the carousel is working fine. 

Over desktop browsers no issues as we can scroll up and down using mouse wheel but the issue only occur over phone touch screen. I am using iPhone 11 safari for testing.

Thank you

**Comment by sag1v** [comment]
Thanks you. Can you create a minimal sandbox with example so i can try accessing via my phone?

**Comment by emt-mocha** [comment]
hi sag1v,

I am  a newbie here. 
I noticed the same behaviour happens on the sandbox over the url at below:

https://21o46mkwnr.csb.app

When you touch the purple box and try to scroll up or down,  it doesn't  respond but outside the purple box it responding.  :)

**Comment by sag1v** [comment]
@emt-mocha Thanks for the info, this should be fixed (in #41). You can use it with the new 0.5.0 version.

The issue was due to the fact that i passed `preventDefaultTouchmoveEvent` to `Swipeable` (from `react-swipeable`), this will prevent page scroll during touch swipe. I think that in some cases, we would want to prevent the scrolling but not all the time. Hence, i exposed it as a [props](https://sag1v.github.io/react-elastic-carousel/#props).

**Comment by thebiltheory** [comment]
Can I suggest to Add a CHANGELOG to the project?

**Comment by sag1v** [comment]
> Can I suggest adding a CHANGELOG to the project?

Indeed. Not sure why i didn't write one so far 😷

**Comment by sag1v** [comment]
@thebiltheory We do have it now :)
https://github.com/sag1v/react-elastic-carousel/releases
